import { describe, it, expect } from 'vitest';
import {
  generateServerTs,
  generatePackageJson,
  generateTsConfig,
} from '../../src/generator/server-template.js';
import type { NormalizedSpec, AuthScheme } from '../../src/types.js';

const minimalSpec: NormalizedSpec = {
  info: { title: 'My API', version: '2.1.0' },
  servers: [{ url: 'https://api.example.com' }],
  endpoints: [],
  auth: [],
  rawFormat: 'openapi3',
};

const bearerScheme: AuthScheme = {
  name: 'bearerAuth',
  type: 'http',
  scheme: 'bearer',
  envVar: 'MYAPI_BEARER',
};

const apiKeyScheme: AuthScheme = {
  name: 'apiKey',
  type: 'apiKey',
  in: 'header',
  envVar: 'MYAPI_APIKEY',
};

describe('generateServerTs — structure', () => {
  it('includes build-mcp attribution comment', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Generated by build-mcp');
  });

  it('includes API title and version in McpServer config', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('my-api');
    expect(src).toContain('2.1.0');
  });

  it('uses node:sqlite import', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain("from 'node:sqlite'");
  });

  it('ends with server.connect', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('server.connect(transport)');
  });
});

describe('generateServerTs — 2-tool architecture', () => {
  it('registers search_docs tool', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain("'search_docs'");
  });

  it('registers call_api tool', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain("'call_api'");
  });

  it('does NOT register per-endpoint tools', () => {
    const specWithEndpoints: NormalizedSpec = {
      ...minimalSpec,
      endpoints: [
        { id: 'listPets', method: 'GET', path: '/pets', tags: [], parameters: [], responses: [] },
        { id: 'createPet', method: 'POST', path: '/pets', tags: [], parameters: [], responses: [] },
      ],
    };
    const src = generateServerTs(specWithEndpoints, [], 'openai', 'text-embedding-3-small');
    // Should not have tool registrations for individual endpoints
    expect(src).not.toContain("'listPets'");
    expect(src).not.toContain("'createPet'");
    // Should still only have exactly 2 server.tool( calls
    const toolCount = (src.match(/server\.tool\(/g) ?? []).length;
    expect(toolCount).toBe(2);
  });

  it('call_api looks up endpoint from SQLite by ID', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('SELECT endpoint_json FROM endpoints WHERE id = ?');
    expect(src).toContain('endpoint_id');
  });

  it('call_api returns helpful error when endpoint ID is unknown', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Unknown endpoint');
    expect(src).toContain('Available IDs');
  });

  it('call_api accepts params and body inputs', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('params:');
    expect(src).toContain('body:');
  });

  it('call_api substitutes path params into URL', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('path.replace');
    expect(src).toContain('encodeURIComponent');
  });

  it('search_docs uses cosine similarity for ranking', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('_cosineSimilarity');
    expect(src).toContain('.sort((a, b) => b.score - a.score)');
  });

  it('search results include endpoint ID for use in call_api', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('ep.id');
  });
});

describe('generateServerTs — auth', () => {
  it('adds startup warning for each missing env var', () => {
    const src = generateServerTs(minimalSpec, [bearerScheme], 'openai', 'text-embedding-3-small');
    expect(src).toContain('MYAPI_BEARER');
    expect(src).toContain('console.warn');
  });

  it('injects bearer Authorization header in call_api', () => {
    const src = generateServerTs(minimalSpec, [bearerScheme], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Authorization');
    expect(src).toContain('Bearer');
    expect(src).toContain('MYAPI_BEARER');
  });

  it('injects custom header for apiKey scheme', () => {
    const src = generateServerTs(minimalSpec, [apiKeyScheme], 'openai', 'text-embedding-3-small');
    expect(src).toContain('apiKey');
    expect(src).toContain('MYAPI_APIKEY');
  });

  it('shows no authentication comment when no schemes', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('No authentication required');
    // _AUTH is still declared (empty) so call_api doesn't reference an undefined variable
    expect(src).toContain('const _AUTH');
  });

  it('auth headers are injected after ...extraHeaders so they cannot be overwritten', () => {
    const src = generateServerTs(minimalSpec, [bearerScheme], 'openai', 'text-embedding-3-small');
    const extraHeadersIdx = src.indexOf('...extraHeaders');
    const authHeadersIdx = src.indexOf('..._authHeaders');
    expect(extraHeadersIdx).toBeGreaterThan(0);
    expect(authHeadersIdx).toBeGreaterThan(extraHeadersIdx);
  });

  it('auth headers are injected after ...extraHeaders for apiKey schemes too', () => {
    const src = generateServerTs(minimalSpec, [apiKeyScheme], 'openai', 'text-embedding-3-small');
    const extraHeadersIdx = src.indexOf('...extraHeaders');
    const authHeadersIdx = src.indexOf('..._authHeaders');
    expect(extraHeadersIdx).toBeGreaterThan(0);
    expect(authHeadersIdx).toBeGreaterThan(extraHeadersIdx);
  });
});

describe('generateServerTs — embedding providers', () => {
  it('uses OpenAI client when provider is openai', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('OpenAI');
    expect(src).toContain('text-embedding-3-small');
    expect(src).not.toContain('OLLAMA_HOST');
  });

  it('uses Ollama fetch when provider is ollama', () => {
    const src = generateServerTs(minimalSpec, [], 'ollama', 'nomic-embed-text');
    expect(src).toContain('OLLAMA_HOST');
    expect(src).toContain('nomic-embed-text');
    expect(src).not.toContain('new OpenAI');
  });

  it('uses @huggingface/transformers pipeline when provider is local', () => {
    const src = generateServerTs(minimalSpec, [], 'local', 'onnx-community/Qwen3-Embedding-0.6B-ONNX');
    expect(src).toContain('@huggingface/transformers');
    expect(src).toContain('feature-extraction');
    expect(src).toContain('Qwen3-Embedding-0.6B-ONNX');
  });

  it('applies query instruct prefix for local provider', () => {
    const src = generateServerTs(minimalSpec, [], 'local', 'onnx-community/Qwen3-Embedding-0.6B-ONNX');
    expect(src).toContain('Instruct:');
    expect(src).toContain('Query:');
  });

  it('caches local pipeline at module level', () => {
    const src = generateServerTs(minimalSpec, [], 'local', 'onnx-community/Qwen3-Embedding-0.6B-ONNX');
    expect(src).toContain('_localPipeline');
    // should declare it before server.tool, not inside the function
    const pipelineDecl = src.indexOf('let _localPipeline');
    const serverToolDecl = src.indexOf('server.tool(');
    expect(pipelineDecl).toBeLessThan(serverToolDecl);
  });

  it('uses last_token pooling and normalize for local provider', () => {
    const src = generateServerTs(minimalSpec, [], 'local', 'onnx-community/Qwen3-Embedding-0.6B-ONNX');
    expect(src).toContain("pooling: 'last_token'");
    expect(src).toContain('normalize: true');
  });
});

describe('generatePackageJson', () => {
  it('includes openai dep when provider is openai', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'openai'));
    expect(pkg.dependencies).toHaveProperty('openai');
  });

  it('excludes openai when provider is ollama', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'ollama'));
    expect(pkg.dependencies).not.toHaveProperty('openai');
  });

  it('always includes @modelcontextprotocol/sdk and zod', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'openai'));
    expect(pkg.dependencies).toHaveProperty('@modelcontextprotocol/sdk');
    expect(pkg.dependencies).toHaveProperty('zod');
  });

  it('sanitizes package name', () => {
    const pkg = JSON.parse(generatePackageJson('My Cool API!', '1.0.0', 'openai'));
    expect(pkg.name).toBe('my-cool-api-mcp');
  });

  it('does NOT include better-sqlite3 or sqlite-vec', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'openai'));
    expect(pkg.dependencies).not.toHaveProperty('better-sqlite3');
    expect(pkg.dependencies).not.toHaveProperty('sqlite-vec');
  });

  it('includes @huggingface/transformers when provider is local', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'local'));
    expect(pkg.dependencies).toHaveProperty('@huggingface/transformers');
    expect(pkg.dependencies).not.toHaveProperty('openai');
  });

  it('requires node >= 22.5.0', () => {
    const pkg = JSON.parse(generatePackageJson('API', '1.0.0', 'openai'));
    expect(pkg.engines.node).toContain('22');
  });
});

describe('generateServerTs — response schema in search_docs', () => {
  it('search_docs output includes Returns line logic', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Returns (');
    expect(src).toContain('returnsLines');
  });
});

describe('generateServerTs — api-workflows resource', () => {
  it('embeds workflows markdown as WORKFLOWS_MD constant', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small', '# Workflows\n\nSome content');
    expect(src).toContain('WORKFLOWS_MD');
    expect(src).toContain('Some content');
  });

  it('registers api-workflows resource with correct URI', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain("'api-workflows'");
    expect(src).toContain('workflows://guide');
    expect(src).toContain('text/markdown');
  });

  it('resource is registered before server.connect', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    const resourceIdx = src.indexOf('api-workflows');
    const connectIdx = src.indexOf('server.connect(');
    expect(resourceIdx).toBeGreaterThan(0);
    expect(resourceIdx).toBeLessThan(connectIdx);
  });

  it('uses empty string default when workflowsMd is omitted', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('WORKFLOWS_MD = ""');
  });
});

describe('generateServerTs — safety classification', () => {
  it('search_docs result includes safety badge logic', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('safetyLevel');
    expect(src).toContain('BILLABLE');
    expect(src).toContain('DESTRUCTIVE');
    expect(src).toContain('WRITE');
  });
});

describe('generateServerTs — pre-call validation', () => {
  it('generated server includes _validate helper', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('function _validate(');
  });

  it('_validate checks required params', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('is required');
  });

  it('_validate checks enum values', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('must be one of');
  });

  it('_validate checks integer type', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('must be integer');
  });

  it('call_api calls _validate before the HTTP fetch', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    const validateIdx = src.indexOf('_validate(');
    const fetchIdx = src.indexOf('await fetch(url,');
    expect(validateIdx).toBeGreaterThan(0);
    expect(validateIdx).toBeLessThan(fetchIdx);
  });

  it('returns validation error without making HTTP request', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Validation failed');
    expect(src).toContain('fix before calling');
  });
});

describe('generateServerTs — response trimming', () => {
  it('includes _trimResponse helper', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('function _trimResponse(');
  });

  it('call_api uses _trimResponse instead of raw JSON.stringify', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('_trimResponse(data)');
  });

  it('_trimResponse handles top-level arrays', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Array.isArray(data)');
    expect(src).toContain('Array of');
    expect(src).toContain('more items not shown');
  });

  it('_trimResponse handles list-shape responses with data + has_more', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('has_more');
    expect(src).toContain('paginate with');
  });

  it('_trimResponse gives structural summary for large arbitrary objects', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Large response');
    expect(src).toContain('Top-level structure');
  });

  it('_trimResponse truncates strings at 8000 chars', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('const MAX = 8000');
    expect(src).toContain('truncated');
  });

  it('_trimResponse is declared before server.tool(', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    const trimIdx = src.indexOf('function _trimResponse(');
    const toolIdx = src.indexOf('server.tool(');
    expect(trimIdx).toBeGreaterThan(0);
    expect(trimIdx).toBeLessThan(toolIdx);
  });

  it('generated _trimResponse contains valid backtick template literals (no escaped backticks)', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    // Extract _trimResponse body and verify no \\` sequences (which would be invalid TS)
    const start = src.indexOf('function _trimResponse(');
    const end = src.indexOf('\nfunction ', start + 1);
    const trimFn = src.slice(start, end > start ? end : undefined);
    expect(trimFn).not.toContain('\\`');
  });
});

describe('generateTsConfig', () => {
  it('returns valid JSON', () => {
    expect(() => JSON.parse(generateTsConfig())).not.toThrow();
  });

  it('targets ES2022 with NodeNext modules', () => {
    const cfg = JSON.parse(generateTsConfig());
    expect(cfg.compilerOptions.target).toBe('ES2022');
    expect(cfg.compilerOptions.moduleResolution).toBe('NodeNext');
    expect(cfg.compilerOptions.strict).toBe(true);
  });
});
