import { describe, it, expect } from 'vitest';
import {
  generateServerTs,
  generatePackageJson,
  generateTsConfig,
} from '../../src/generator/server-template.js';
import { endpointToTool } from '../../src/generator/tools.js';
import type { NormalizedSpec, AuthScheme, Endpoint } from '../../src/types.js';

const minimalSpec: NormalizedSpec = {
  info: { title: 'My API', version: '2.1.0' },
  servers: [{ url: 'https://api.example.com' }],
  endpoints: [],
  auth: [],
  rawFormat: 'openapi3',
};

const petEndpoint: Endpoint = {
  id: 'listPets',
  operationId: 'listPets',
  method: 'GET',
  path: '/pets',
  summary: 'List all pets',
  tags: ['pets'],
  parameters: [{ name: 'limit', in: 'query', required: false, schema: { type: 'integer' } }],
  responses: [{ statusCode: '200', description: 'OK' }],
};

const bearerScheme: AuthScheme = {
  name: 'bearerAuth',
  type: 'http',
  scheme: 'bearer',
  envVar: 'MYAPI_BEARER',
};

describe('generateServerTs', () => {
  it('includes the API title in the McpServer name', () => {
    const tools = [endpointToTool(petEndpoint, 'https://api.example.com', '{}', '')];
    const src = generateServerTs(minimalSpec, tools, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('my-api');
  });

  it('includes the API version', () => {
    const src = generateServerTs(minimalSpec, [], [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('2.1.0');
  });

  it('includes mcpify attribution comment', () => {
    const src = generateServerTs(minimalSpec, [], [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Generated by mcpify');
  });

  it('includes the search_api_docs tool', () => {
    const src = generateServerTs(minimalSpec, [], [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('search_api_docs');
  });

  it('includes cosine similarity function', () => {
    const src = generateServerTs(minimalSpec, [], [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('_cosineSimilarity');
  });

  it('uses node:sqlite import', () => {
    const src = generateServerTs(minimalSpec, [], [], 'openai', 'text-embedding-3-small');
    expect(src).toContain("from 'node:sqlite'");
  });

  it('adds auth warning when schemes are present', () => {
    const src = generateServerTs(minimalSpec, [], [bearerScheme], 'openai', 'text-embedding-3-small');
    expect(src).toContain('MYAPI_BEARER');
    expect(src).toContain('console.warn');
  });

  it('generates OpenAI embed function when provider is openai', () => {
    const src = generateServerTs(minimalSpec, [], [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('OpenAI');
    expect(src).toContain('text-embedding-3-small');
  });

  it('generates Ollama embed function when provider is ollama', () => {
    const src = generateServerTs(minimalSpec, [], [], 'ollama', 'nomic-embed-text');
    expect(src).toContain('OLLAMA_HOST');
    expect(src).toContain('nomic-embed-text');
    expect(src).not.toContain('OpenAI');
  });

  it('registers each tool', () => {
    const tools = [endpointToTool(petEndpoint, 'https://api.example.com', '{}', '')];
    const src = generateServerTs(minimalSpec, tools, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain("'listPets'");
    expect(src).toContain('List all pets');
  });

  it('ends with server.connect call', () => {
    const src = generateServerTs(minimalSpec, [], [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('server.connect(transport)');
  });
});

describe('generatePackageJson', () => {
  it('includes openai dependency when provider is openai', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'openai'));
    expect(pkg.dependencies).toHaveProperty('openai');
  });

  it('excludes openai when provider is ollama', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'ollama'));
    expect(pkg.dependencies).not.toHaveProperty('openai');
  });

  it('always includes @modelcontextprotocol/sdk and zod', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'openai'));
    expect(pkg.dependencies).toHaveProperty('@modelcontextprotocol/sdk');
    expect(pkg.dependencies).toHaveProperty('zod');
  });

  it('sanitizes package name from API title', () => {
    const pkg = JSON.parse(generatePackageJson('My Cool API!', '1.0.0', 'openai'));
    expect(pkg.name).toBe('my-cool-api-mcp');
  });

  it('requires node >= 22.5.0', () => {
    const pkg = JSON.parse(generatePackageJson('API', '1.0.0', 'openai'));
    expect(pkg.engines.node).toContain('22');
  });
});

describe('generateTsConfig', () => {
  it('returns valid JSON', () => {
    expect(() => JSON.parse(generateTsConfig())).not.toThrow();
  });

  it('targets ES2022', () => {
    const cfg = JSON.parse(generateTsConfig());
    expect(cfg.compilerOptions.target).toBe('ES2022');
  });

  it('uses NodeNext module resolution', () => {
    const cfg = JSON.parse(generateTsConfig());
    expect(cfg.compilerOptions.moduleResolution).toBe('NodeNext');
  });

  it('enables strict mode', () => {
    const cfg = JSON.parse(generateTsConfig());
    expect(cfg.compilerOptions.strict).toBe(true);
  });
});
