import { mkdirSync, writeFileSync, cpSync } from 'fs';
import { join } from 'path';
import type { NormalizedSpec, GenerateOptions, EmbedConfig } from '../types.js';
import { ApiIndexer } from '../indexer/index.js';
import { endpointToTool } from './tools.js';
import { extractRequiredEnvVars, buildAuthHeaders, buildAuthQueryParams, buildDotEnvExample } from './auth.js';
import { generateServerTs, generatePackageJson, generateTsConfig } from './server-template.js';

export interface GenerateResult {
  outputDir: string;
  endpointsIndexed: number;
  envVars: Array<{ name: string; description: string }>;
}

export async function generateMcpServer(
  spec: NormalizedSpec,
  options: GenerateOptions,
): Promise<GenerateResult> {
  const provider = options.embeddingProvider ?? 'openai';
  const model = options.embeddingModel ?? (provider === 'openai' ? 'text-embedding-3-small' : 'nomic-embed-text');
  const baseUrl = options.baseUrl ?? spec.servers[0]?.url ?? 'https://api.example.com';
  const name = options.name ?? spec.info.title;

  const embedConfig: EmbedConfig = { provider, model };

  // Create output structure
  const outDir = options.outputDir;
  const srcDir = join(outDir, 'src');
  const dbDir = join(outDir, 'db');

  mkdirSync(srcDir, { recursive: true });
  mkdirSync(dbDir, { recursive: true });

  // Index endpoints into SQLite
  const dbPath = join(dbDir, 'api.sqlite');
  const indexer = new ApiIndexer(dbPath);
  await indexer.indexSpec(spec, embedConfig);
  indexer.close();

  // Generate auth info
  const authHeaders = buildAuthHeaders(spec.auth);
  const authQueryParams = buildAuthQueryParams(spec.auth);
  const envVars = extractRequiredEnvVars(spec.auth, spec.endpoints);

  // Generate tools
  const tools = spec.endpoints.map(ep =>
    endpointToTool(ep, baseUrl, authHeaders, authQueryParams)
  );

  // Write server.ts
  const serverTs = generateServerTs(spec, tools, spec.auth, provider, model);
  writeFileSync(join(srcDir, 'server.ts'), serverTs);

  // Write package.json
  const pkgJson = generatePackageJson(name, spec.info.version, provider);
  writeFileSync(join(outDir, 'package.json'), pkgJson);

  // Write tsconfig.json
  writeFileSync(join(outDir, 'tsconfig.json'), generateTsConfig());

  // Write .env.example
  const dotEnv = buildDotEnvExample(envVars);
  writeFileSync(join(outDir, '.env.example'), dotEnv);

  // Write README
  writeFileSync(join(outDir, 'README.md'), generateReadme(spec, envVars, provider));

  return {
    outputDir: outDir,
    endpointsIndexed: spec.endpoints.length,
    envVars,
  };
}

function generateReadme(
  spec: NormalizedSpec,
  envVars: Array<{ name: string; description: string }>,
  provider: string,
): string {
  const envSection = envVars.length > 0
    ? `## Required environment variables\n\n${envVars.map(v => `- \`${v.name}\` — ${v.description}`).join('\n')}\n`
    : '';

  const providerNote = provider === 'openai'
    ? '- `OPENAI_API_KEY` — required for the `search_api_docs` tool'
    : `- Configure \`OLLAMA_HOST\` if Ollama is not on localhost`;

  return `# ${spec.info.title} MCP Server

Generated by [mcpify](https://github.com/bisratttt/mcpify).

${spec.info.description ? spec.info.description + '\n' : ''}
## Setup

\`\`\`bash
npm install
cp .env.example .env
# Fill in your credentials
npm run dev
\`\`\`

${envSection}
## Embedding / search

${providerNote}

## Tools

This server exposes **${spec.endpoints.length} API tools** plus a \`search_api_docs\` tool for RAG-powered discovery.

Start by calling \`search_api_docs\` to find relevant endpoints before calling them directly.
`;
}
