import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { NormalizedSpec, GenerateOptions, EmbedConfig, EmbeddingProvider } from '../types.js';
import { ApiIndexer } from '../indexer/index.js';
import { QWEN3_MODEL } from '../indexer/embed.js';
import { extractRequiredEnvVars, buildDotEnvExample } from './auth.js';
import { generateServerTs, generatePackageJson, generateTsConfig } from './server-template.js';

function defaultModel(provider: EmbeddingProvider): string {
  switch (provider) {
    case 'openai': return 'text-embedding-3-small';
    case 'ollama': return 'nomic-embed-text';
    case 'local':  return QWEN3_MODEL;
  }
}

export interface GenerateResult {
  outputDir: string;
  endpointsIndexed: number;
  envVars: Array<{ name: string; description: string }>;
}

export async function generateMcpServer(
  spec: NormalizedSpec,
  options: GenerateOptions,
): Promise<GenerateResult> {
  const provider = options.embeddingProvider ?? 'local';
  const model = options.embeddingModel ?? defaultModel(provider);
  const name = options.name ?? spec.info.title;

  // Override base URL if provided
  const specWithBaseUrl: NormalizedSpec = options.baseUrl
    ? { ...spec, servers: [{ url: options.baseUrl }, ...spec.servers] }
    : spec;

  const embedConfig: EmbedConfig = { provider, model };

  const outDir = options.outputDir;
  mkdirSync(join(outDir, 'src'), { recursive: true });
  mkdirSync(join(outDir, 'db'), { recursive: true });

  // Index all endpoints into SQLite with embeddings
  const indexer = new ApiIndexer(join(outDir, 'db', 'api.sqlite'));
  await indexer.indexSpec(specWithBaseUrl, embedConfig);
  indexer.close();

  const envVars = extractRequiredEnvVars(spec.auth, spec.endpoints);

  writeFileSync(join(outDir, 'src', 'server.ts'), generateServerTs(specWithBaseUrl, spec.auth, provider, model));
  writeFileSync(join(outDir, 'package.json'), generatePackageJson(name, spec.info.version, provider));
  writeFileSync(join(outDir, 'tsconfig.json'), generateTsConfig());
  writeFileSync(join(outDir, '.env.example'), buildDotEnvExample(envVars));
  writeFileSync(join(outDir, 'README.md'), generateReadme(specWithBaseUrl, envVars, provider));

  return { outputDir: outDir, endpointsIndexed: spec.endpoints.length, envVars };
}

function generateReadme(
  spec: NormalizedSpec,
  envVars: Array<{ name: string; description: string }>,
  provider: string,
): string {
  const envSection = envVars.length > 0
    ? `## Required environment variables\n\n${envVars.map(v => `- \`${v.name}\` — ${v.description}`).join('\n')}\n`
    : '';

  const providerNote = provider === 'openai'
    ? '- `OPENAI_API_KEY` — required for the `search_api_docs` tool'
    : '- Configure `OLLAMA_HOST` if Ollama is not on localhost';

  return `# ${spec.info.title} MCP Server

Generated by [apimcp](https://github.com/bisratttt/apimcp).

${spec.info.description ? spec.info.description + '\n' : ''}
## Setup

\`\`\`bash
npm install
cp .env.example .env
npm start
\`\`\`

${envSection}
## Tools

This server exposes exactly **2 tools** regardless of how many endpoints the API has:

- \`search_docs\` — semantic search over all ${spec.endpoints.length} endpoints; returns IDs and parameter schemas
- \`call_api\` — executes any endpoint by ID with the params you provide

Always call \`search_docs\` first to find the right endpoint ID, then call \`call_api\` with it.

## Embedding / search

${providerNote}
`;
}
