import type { NormalizedSpec, AuthScheme, EmbeddingProvider } from '../types.js';
import type { AuthEnvVar } from './auth.js';

/**
 * Generates a 2-tool MCP server:
 *   1. search_api_docs — semantic search over all indexed endpoints
 *   2. call_api        — dynamic executor: loads endpoint from SQLite, makes the HTTP call
 *
 * This keeps tool count at 2 regardless of how many endpoints the API has,
 * so connecting agents never get their context bloated by hundreds of tool schemas.
 */
export function generateServerTs(
  spec: NormalizedSpec,
  authSchemes: AuthScheme[],
  embeddingProvider: EmbeddingProvider,
  embeddingModel: string,
): string {
  const baseUrl = spec.servers[0]?.url ?? 'https://api.example.com';
  const hasAuth = authSchemes.length > 0;

  return `/**
 * Generated by apimcp — https://github.com/bisratttt/apimcp
 * API: ${spec.info.title} v${spec.info.version}
 * DO NOT EDIT — re-run apimcp to regenerate
 */
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Auth ─────────────────────────────────────────────────────────────────────
${hasAuth ? generateAuthSection(authSchemes) : '// No authentication required'}

const _BASE_URL = '${baseUrl}';
const _db = new DatabaseSync(join(__dirname, '..', 'db', 'api.sqlite'));
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _localPipeline: any = null;

// ── Helpers ───────────────────────────────────────────────────────────────────
function _cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i]; normA += a[i] * a[i]; normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB) || 1);
}

function _bufToFloats(raw: Uint8Array): number[] {
  const view = new DataView(raw.buffer, raw.byteOffset, raw.byteLength);
  const arr: number[] = [];
  for (let i = 0; i < raw.byteLength; i += 4) arr.push(view.getFloat32(i, true));
  return arr;
}

async function _embed(text: string): Promise<number[]> {
  ${generateEmbedFunction(embeddingProvider, embeddingModel)}
}

// ── Pre-call validation ───────────────────────────────────────────────────────
function _validate(
  parameters: Array<{ name: string; in: string; required: boolean; schema?: { type?: string; enum?: unknown[] } }>,
  params: Record<string, unknown>,
): string[] {
  const errors: string[] = [];
  for (const p of parameters) {
    const val = params[p.name];
    if (p.required && val === undefined) {
      errors.push(\`'\${p.name}' (\${p.in}) is required\`);
      continue;
    }
    if (val === undefined || !p.schema) continue;
    const { type, enum: allowed } = p.schema;
    if (allowed && !allowed.includes(val)) {
      errors.push(\`'\${p.name}' must be one of: \${(allowed as string[]).join('|')}, got: \${JSON.stringify(val)}\`);
    } else if (type === 'integer' && !Number.isInteger(val)) {
      errors.push(\`'\${p.name}' must be integer, got: \${typeof val}\`);
    } else if (type === 'number' && typeof val !== 'number') {
      errors.push(\`'\${p.name}' must be number, got: \${typeof val}\`);
    } else if (type === 'boolean' && typeof val !== 'boolean') {
      errors.push(\`'\${p.name}' must be boolean, got: \${typeof val}\`);
    }
  }
  return errors;
}

// ── Response trimming ─────────────────────────────────────────────────────────
${generateTrimResponseHelper()}

// ── Server ────────────────────────────────────────────────────────────────────
const server = new McpServer({
  name: '${sanitizeId(spec.info.title)}',
  version: '${spec.info.version}',
});

// ── Tool 1: search_docs ───────────────────────────────────────────────────────
server.tool(
  'search_docs',
  \`Search the ${spec.info.title} API documentation. Returns matching endpoint IDs and their parameter schemas. Always call this before call_api if you don't already know the exact endpoint ID.\`,
  {
    query: z.string().describe('What you want to do, in plain English'),
    limit: z.number().int().min(1).max(20).optional().default(5),
  },
  async ({ query, limit }) => {
    const queryVec = await _embed(query);
    const rows = _db.prepare(
      'SELECT endpoint_json, embedding FROM endpoints WHERE embedding IS NOT NULL'
    ).all() as { endpoint_json: string; embedding: Uint8Array }[];

    const scored = rows
      .map(r => ({ ep: JSON.parse(r.endpoint_json) as Record<string, unknown>, score: _cosineSimilarity(queryVec, _bufToFloats(r.embedding)) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, limit ?? 5);

    if (scored.length === 0) {
      return { content: [{ type: 'text' as const, text: 'No matching endpoints found.' }] };
    }

    const text = scored.map(({ ep }) => {
      const params = (ep.parameters as Array<{ name: string; in: string; required: boolean; schema?: { type?: string; enum?: unknown[] } }> ?? [])
        .filter(p => p.in !== 'header')
        .map(p => {
          const type = p.schema?.enum ? \`string: \${p.schema.enum.join('|')}\` : (p.schema?.type ?? 'string');
          return \`\${p.name} (\${p.in}, \${p.required ? 'required' : 'optional'}, \${type})\`;
        });
      const body = ep.requestBody as { required: boolean; contentType: string; schema?: { properties?: Record<string, { type?: string }> } } | undefined;
      const bodyFields = body?.schema?.properties
        ? \` — {\${Object.entries(body.schema.properties).slice(0, 8).map(([k, v]) => \`\${k}: \${(v as Record<string, unknown>).type ?? 'any'}\`).join(', ')}}\`
        : '';
      const safetyBadge = ep.safetyLevel === 'billable' ? ' 💸 BILLABLE'
        : ep.safetyLevel === 'destructive' ? ' ⚠️ DESTRUCTIVE'
        : ep.safetyLevel === 'write' ? ' [WRITE]'
        : '';
      return [
        \`\${ep.id} (\${ep.method} \${ep.path})\${safetyBadge}\${ep.deprecated ? ' ⚠️ DEPRECATED' : ''}\`,
        \`  \${ep.summary ?? ep.description ?? '(no description)'}\`,
        params.length ? \`  Params: \${params.join(', ')}\` : null,
        body ? \`  Body: \${body.required ? 'required' : 'optional'} (\${body.contentType})\${bodyFields}\` : null,
      ].filter(Boolean).join('\\n');
    }).join('\\n\\n');

    return { content: [{ type: 'text' as const, text }] };
  },
);

// ── Tool 2: call_api ──────────────────────────────────────────────────────────
server.tool(
  'call_api',
  \`Call a ${spec.info.title} API endpoint. Use search_docs first to get the endpoint ID and required params.\`,
  {
    endpoint_id: z.string().describe('Endpoint ID from search_api_docs'),
    params: z.record(z.unknown()).optional().describe('Path, query, and header parameters keyed by name'),
    body: z.unknown().optional().describe('Request body for POST/PUT/PATCH requests'),
  },
  async ({ endpoint_id, params = {}, body }) => {
    const row = _db.prepare('SELECT endpoint_json FROM endpoints WHERE id = ?').get(endpoint_id) as { endpoint_json: string } | undefined;
    if (!row) {
      const available = (_db.prepare('SELECT id FROM endpoints').all() as { id: string }[]).map(r => r.id).join(', ');
      return { content: [{ type: 'text' as const, text: \`Unknown endpoint "\${endpoint_id}". Available IDs: \${available}\` }] };
    }

    const ep = JSON.parse(row.endpoint_json) as {
      method: string;
      path: string;
      parameters: Array<{ name: string; in: string; required: boolean; schema?: { type?: string; enum?: unknown[] } }>;
      requestBody?: { contentType: string };
      safetyLevel?: string;
    };

    const validationErrors = _validate(ep.parameters, params as Record<string, unknown>);
    if (validationErrors.length) {
      return { content: [{ type: 'text' as const, text: \`Validation failed — fix before calling:\\n\${validationErrors.map(e => \`• \${e}\`).join('\\n')}\` }] };
    }

    const isGraphQL = ep.method.startsWith('GRAPHQL_');

    if (isGraphQL) {
      ${generateGraphQLCallSection()}
    }

    // Build URL
    let path = ep.path;
    const qs = new URLSearchParams();
    const extraHeaders: Record<string, string> = {};

    for (const param of ep.parameters) {
      const val = (params as Record<string, unknown>)[param.name];
      if (val === undefined) continue;
      if (param.in === 'path') {
        path = path.replace(\`{\${param.name}}\`, encodeURIComponent(String(val)));
      } else if (param.in === 'query') {
        qs.set(param.name, String(val));
      } else if (param.in === 'header') {
        extraHeaders[param.name] = String(val);
      }
    }

    const url = \`\${_BASE_URL}\${path}\${qs.toString() ? '?' + qs.toString() : ''}\`;
    const method = ep.method;
    const hasBody = body !== undefined && !['GET', 'HEAD'].includes(method);

    const res = await fetch(url, {
      method,
      headers: {
        'Content-Type': ep.requestBody?.contentType ?? 'application/json',
        ${generateAuthHeaders(authSchemes)}
        ...extraHeaders,
      },
      body: hasBody ? JSON.stringify(body) : undefined,
    });

    const data = await res.json().catch(() => res.text());
    return { content: [{ type: 'text' as const, text: _trimResponse(data) }] };
  },
);

// ── Start ─────────────────────────────────────────────────────────────────────
const transport = new StdioServerTransport();
await server.connect(transport);
`;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function generateAuthSection(schemes: AuthScheme[]): string {
  const checks = schemes
    .map(s => `if (!process.env.${s.envVar}) console.warn('[apimcp] Warning: ${s.envVar} is not set');`)
    .join('\n');
  return `// Auth — check required env vars at startup\n${checks}`;
}

function generateAuthHeaders(schemes: AuthScheme[]): string {
  const lines = schemes.flatMap(s => {
    if (s.type === 'apiKey' && s.in === 'header') {
      return [`        '${s.name}': process.env.${s.envVar} ?? '',`];
    }
    if (s.type === 'http' || s.type === 'oauth2') {
      const prefix = s.scheme === 'basic' ? 'Basic' : 'Bearer';
      return [`        'Authorization': \`${prefix} \${process.env.${s.envVar} ?? ''}\`,`];
    }
    return [];
  });
  return lines.join('\n');
}

function generateGraphQLCallSection(): string {
  return `
      const opType = ep.method === 'GRAPHQL_MUTATION' ? 'mutation' : 'query';
      const opName = (ep as { operationId?: string }).operationId ?? endpoint_id;
      const vars = params as Record<string, unknown>;
      const gqlRes = await fetch(\`\${_BASE_URL}\${ep.path}\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: \`\${opType} { \${opName} }\`, variables: vars }),
      });
      const gqlData = await gqlRes.json();
      return { content: [{ type: 'text' as const, text: JSON.stringify(gqlData, null, 2) }] };`;
}

function generateEmbedFunction(provider: EmbeddingProvider, model: string): string {
  if (provider === 'openai') {
    return `
  const { default: OpenAI } = await import('openai');
  const res = await new OpenAI({ apiKey: process.env.OPENAI_API_KEY }).embeddings.create({ model: '${model}', input: text });
  return res.data[0].embedding;`;
  }
  if (provider === 'ollama') {
    return `
  const baseUrl = process.env.OLLAMA_HOST ?? 'http://localhost:11434';
  const res = await fetch(\`\${baseUrl}/api/embeddings\`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: '${model}', prompt: text }),
  });
  return (await res.json() as { embedding: number[] }).embedding;`;
  }
  // local — Qwen3-Embedding via @huggingface/transformers
  // Pipeline is cached at module level so it's only loaded once
  return `
  if (!_localPipeline) {
    const { pipeline } = await import('@huggingface/transformers');
    process.stderr.write('[apimcp] Loading embedding model (first run downloads ~614MB — please wait)...\\n');
    _localPipeline = await pipeline('feature-extraction', '${model}', { dtype: 'q8' });
    process.stderr.write('[apimcp] Embedding model ready.\\n');
  }
  const _task = 'Given a search query, retrieve relevant API endpoints that match the user intent';
  const _input = \`Instruct: \${_task}\\nQuery:\${text}\`;
  const _out = await _localPipeline([_input], { pooling: 'last_token', normalize: true });
  return (_out.tolist() as number[][])[0];`;
}

export function generatePackageJson(name: string, version: string, embeddingProvider: EmbeddingProvider): string {
  return JSON.stringify({
    name: `${sanitizeId(name)}-mcp`,
    version: version || '1.0.0',
    description: `MCP server for ${name} — generated by apimcp`,
    type: 'module',
    scripts: { start: 'tsx src/server.ts', build: 'tsc' },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.10.0',
      zod: '^3.23.8',
      tsx: '^4.19.0',
      ...(embeddingProvider === 'openai' ? { openai: '^4.52.0' } : {}),
      ...(embeddingProvider === 'local' ? { '@huggingface/transformers': '^3.8.1' } : {}),
    },
    devDependencies: { '@types/node': '^22.0.0', typescript: '^5.5.0' },
    engines: { node: '>=22.5.0' },
  }, null, 2) + '\n';
}

export function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext',
      outDir: './dist', rootDir: './src', strict: true, esModuleInterop: true, skipLibCheck: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  }, null, 2) + '\n';
}

function sanitizeId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

function generateTrimResponseHelper(): string {
  return `function _trimResponse(data: unknown): string {
  const MAX = 8000;

  // Top-level array — count + first item
  if (Array.isArray(data)) {
    const raw = JSON.stringify(data, null, 2);
    if (raw.length <= MAX) return raw;
    return \`Array of \${data.length} items. First item:\\n\${JSON.stringify(data[0], null, 2)}\\n\\n[\${data.length - 1} more items not shown — use filter/search params if available.]\`;
  }

  if (data && typeof data === 'object') {
    const d = data as Record<string, unknown>;

    // List shape: { data: [...], has_more? } — Stripe, many REST APIs
    if (Array.isArray(d['data']) && (d['data'] as unknown[]).length > 0) {
      const list = d['data'] as unknown[];
      const raw = JSON.stringify(data, null, 2);
      if (raw.length <= MAX) return raw;
      const hasMore = d['has_more'] ?? false;
      const lines = [\`\${list.length} items\${hasMore ? ' (has_more: true — paginate with starting_after/page_token)' : ''}\`];
      lines.push(\`First: \${JSON.stringify(list[0])}\`);
      if (list.length > 1) lines.push(\`Last:  \${JSON.stringify(list[list.length - 1])}\`);
      return lines.join('\\n');
    }

    // Large arbitrary object — structural summary of top-level keys
    const raw = JSON.stringify(data, null, 2);
    if (raw.length <= MAX) return raw;
    const lines = [\`Large response (\${(raw.length / 1024).toFixed(1)}KB). Top-level structure:\`];
    for (const [k, v] of Object.entries(d)) {
      if (Array.isArray(v)) {
        lines.push(\`  \${k}: array[\${v.length}]\${v.length ? ' — first: ' + JSON.stringify(v[0]).slice(0, 120) : ''}\`);
      } else if (v && typeof v === 'object') {
        lines.push(\`  \${k}: object{keys: \${Object.keys(v as object).join(', ')}}\`);
      } else {
        lines.push(\`  \${k}: \${JSON.stringify(v)}\`);
      }
    }
    return lines.join('\\n');
  }

  // Primitive or string fallback
  const raw = String(data);
  return raw.length <= MAX ? raw : raw.slice(0, MAX) + \`\\n[truncated — \${raw.length - MAX} more chars]\`;
}`;
}
