import type { NormalizedSpec, AuthScheme, EmbeddingProvider } from '../types.js';
import type { McpToolDefinition } from './tools.js';
import type { AuthEnvVar } from './auth.js';

export function generateServerTs(
  spec: NormalizedSpec,
  tools: McpToolDefinition[],
  authSchemes: AuthScheme[],
  embeddingProvider: EmbeddingProvider,
  embeddingModel: string,
): string {
  const hasAuth = authSchemes.length > 0;
  const toolRegistrations = tools.map(t => generateToolRegistration(t)).join('\n\n');

  return `/**
 * Generated by mcpify — https://github.com/bisratttt/mcpify
 * API: ${spec.info.title} v${spec.info.version}
 * DO NOT EDIT — re-run mcpify to regenerate
 */
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

${hasAuth ? generateAuthCheck(authSchemes) : '// No authentication required'}

const _db = new DatabaseSync(join(__dirname, '..', 'db', 'api.sqlite'));

function _cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB) || 1);
}

function _bufToFloats(buf: Buffer): number[] {
  const arr: number[] = [];
  for (let i = 0; i < buf.length; i += 4) arr.push(buf.readFloatLE(i));
  return arr;
}

async function _embed(text: string): Promise<number[]> {
  ${generateEmbedFunction(embeddingProvider, embeddingModel)}
}

const server = new McpServer({
  name: '${sanitizeId(spec.info.title)}',
  version: '${spec.info.version}',
});

// ── Search tool ──────────────────────────────────────────────────────────────
server.tool(
  'search_api_docs',
  'Search the API documentation using natural language. Use this to discover available endpoints before calling them.',
  {
    query: z.string().describe('Natural language search query'),
    limit: z.number().int().min(1).max(20).optional().default(5).describe('Max results to return'),
  },
  async ({ query, limit }) => {
    const queryVec = await _embed(query);
    const rows = _db.prepare(
      'SELECT endpoint_json, embedding FROM endpoints WHERE embedding IS NOT NULL'
    ).all() as { endpoint_json: string; embedding: Buffer }[];

    const scored = rows.map(r => ({
      ep: JSON.parse(r.endpoint_json) as Record<string, unknown>,
      score: _cosineSimilarity(queryVec, _bufToFloats(r.embedding)),
    }));
    scored.sort((a, b) => b.score - a.score);

    const results = scored.slice(0, limit ?? 5).map(({ ep }) =>
      \`\${ep.method} \${ep.path}\\n  \${ep.summary ?? ep.description ?? '(no description)'}\\n  Tool: \${ep.id}\`
    ).join('\\n\\n');

    return {
      content: [{ type: 'text' as const, text: results || 'No matching endpoints found.' }],
    };
  },
);

// ── API tools ────────────────────────────────────────────────────────────────
${toolRegistrations}

// ── Start ────────────────────────────────────────────────────────────────────
const transport = new StdioServerTransport();
await server.connect(transport);
`;
}

function generateAuthCheck(schemes: AuthScheme[]): string {
  const checks = schemes.map(s =>
    `  if (!process.env.${s.envVar}) console.warn('[mcpify] Warning: ${s.envVar} is not set — ${s.name} auth will fail');`
  ).join('\n');
  return `// Auth validation\n${checks}`;
}

function generateEmbedFunction(provider: EmbeddingProvider, model: string): string {
  if (provider === 'openai') {
    return `
  const { default: OpenAI } = await import('openai');
  const _client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const res = await _client.embeddings.create({ model: '${model}', input: text });
  return res.data[0].embedding;`;
  }
  // ollama
  return `
  const baseUrl = process.env.OLLAMA_HOST ?? 'http://localhost:11434';
  const res = await fetch(\`\${baseUrl}/api/embeddings\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: '${model}', prompt: text }),
  });
  const data = await res.json() as { embedding: number[] };
  return data.embedding;`;
}

function generateToolRegistration(tool: McpToolDefinition): string {
  const schemaFields = tool.inputSchema.fields.map(f => {
    const zodExpr = f.optional ? `${f.zodType}.optional()` : f.zodType;
    return `    ${f.name}: ${zodExpr},`;
  }).join('\n');

  const schemaArg = tool.inputSchema.fields.length > 0
    ? `{\n${schemaFields}\n  }`
    : '{}';

  return `server.tool(
  '${tool.name}',
  ${JSON.stringify(tool.description)},
  ${schemaArg},
  ${tool.implementation},
);`;
}

export function generatePackageJson(name: string, version: string, embeddingProvider: EmbeddingProvider): string {
  return JSON.stringify({
    name: `${sanitizeId(name)}-mcp`,
    version: version || '1.0.0',
    description: `MCP server for ${name} — generated by mcpify`,
    type: 'module',
    scripts: {
      build: 'tsc',
      start: 'node dist/server.js',
      dev: 'tsx src/server.ts',
    },
    dependencies: Object.fromEntries([
      ['@modelcontextprotocol/sdk', '^1.10.0'],
      ['zod', '^3.23.8'],
      ...(embeddingProvider === 'openai' ? [['openai', '^4.52.0']] : []),
    ]),
    devDependencies: {
      '@types/node': '^22.0.0',
      tsx: '^4.16.0',
      typescript: '^5.5.0',
    },
    engines: { node: '>=22.5.0' },
  }, null, 2) + '\n';
}

export function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      outDir: './dist',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  }, null, 2) + '\n';
}

function sanitizeId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}
